#!/bin/sh

########################################
# Runs MRF MDL Postprocessing
########################################

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir $DATA
cd $DATA 

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

#
# Set up RUN and cycle specific variables
#
export NET=gfs_mos
export RUN=mdlmrfsvr
export fend=00
export finc=3
export fstart=00
export RUN=mdlmrfsvr
export GRIB=""
export EXT=""
export DBN_ALERT_TYPE=MDLMRF_GEMPAK

export HOMEmdl=${HOMEmdl:-$NWROOT/gfsmos.${gfsmos_ver}}
export FIXGEMPAKmdl=${FIXGEMPAKmdl:-$HOMEmdl/gempak/fix}

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/gfsmos.${PDY}}
export COMOUT=${COMOUT:-$COMROOT/${NET}/${envir}/gfsmos.${PDY}/gempak}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
#
# Copy special version of ncepgrib2.tbl file into CWD
#
cp $FIXGEMPAKmdl/mdl_ncepgrib2.tbl $DATA/ncepgrib2.tbl

env

########################################################
# Execute the script.
$HOMEmdl/scripts/exnawips_mdl.sh.ecf
########################################################

cat $pgmout

cd $DATAROOT
if [ $KEEPDATA != YES ]; then rm -rf $DATA; fi

date
